containers.yml: Fail if a single job in the matrix failed

diff --git a/.github/workflows/containers.yml b/.github/workflows/containers.yml
--- a/.github/workflows/containers.yml
+++ b/.github/workflows/containers.yml
@@ -96,3 +96,16 @@ jobs:
             ! -name ".wget-hsts" \
           \) -print0 |
           xargs -0 -I{} bash -c 'if ! diff -C 30 "/tmp/old_home/$1" "$1"; then echo "diff failed for: $1"; exit 1; fi' bash {}
+
+  check-results:
+    runs-on: ubuntu-22.04
+    needs: distro-test
+    steps:
+      - name: Check distro-test results
+        run: |
+          for job in ${{ toJSON(needs.distro-test.outputs) }}; do
+            if [[ $job == *"failure"* ]]; then
+              echo "A job in the matrix failed.";
+              exit 1;
+            fi
+          done
